export class User {
  _id: string;
  first_name: string;
  last_name: string;
  nic: string;
  primarynic: string;
  dob: Date;
  phone: string;
  address1: string;
  address2: string;
  town: string;
  district: string;
  dose1: string;
  Dose1_date: Date;
  dose2: string;
  Dose2_date: Date;
  dose3: string;
  Dose3_date: Date;
  idimg1_destination: String;
  idimg2_destination: String;
  vcardimg1_destination: String;
  vcardimg2_destination: String;
  userimg_destination: String;
  idimg1_filename: String;
  idimg2_filename: String;
  vcardimg1_filename: String;
  vcardimg2_filename: String;
  userimg_filename: String;
}
